### ISSUE TITLE
Allow to override Campaign Model?

### ISSUE THREAD

**Issue by bashu** [arneb/django-campaign#10]
subj

**Comment by bashu** [comment]
@arneb what do you think about https://github.com/wq/django-swappable-models ?

**Comment by arneb** [comment]
why should we use an app, if the mechanism is a django-builtin?

**Comment by bashu** [comment]
@arneb maybe because builtin feature undocumented? have you tried it yourself (I'm not talking about custom user model)

**Comment by bashu** [comment]
check #13

**Comment by bashu** [comment]
if someone interested here is another fork https://github.com/bashu/fluentcms-campaign

**Comment by arneb** [comment]
see response in PR #10 and #13

**Comment by arneb** [comment]
> @arneb maybe because builtin feature undocumented? have you tried it yourself (I'm not talking about custom user model)

yes, I've used it successfully in two cases (not talking about user model).

**Comment by bashu** [comment]
why it was closed?
