### ISSUE TITLE
support for django 2.2 on pypi released version

### ISSUE THREAD

**Issue by blighj** [arneb/django-campaign#24]
It looks like the version on pypi doesn't have the fixes to support django 2.2
Would be great to have them up there.

**Comment by arneb** [comment]
good catch! Did you test with the current master branch and everything works with Django 2.2?

**Comment by blighj** [comment]
Yes have tested the current master in 2.2 and all is working as expected.

**Comment by 9mido** [comment]
Does this work with django 3.1?

**Comment by arneb** [comment]
Version 0.5.0 is now available on PyPI
