### ISSUE TITLE
How i can use the subscriber list in admin?

### ISSUE THREAD

**Issue by fr33co** [arneb/django-campaign#3]
I don't understand the format or the method to create subscriber list. How is the format of the json field? Sorry for my english.

**Comment by emetor** [comment]
Hello,

You can simply select for example

Content type: user
Filter condition {"is_active": true}

Hope that helps.

Best regards,
Stephan

**Comment by arneb** [comment]
Hi fr33co,

the documentation is not covering this topic very good :-(

The Json-Field expects a json encoded dict of kwargs, which get passed to the QuerySet. 
emetor already gave a good example!
So ContentType "user" and filter ```{"is_active": true}``` will map to: ```User.objects.filter(is_active=True)```

Best regards,
Arne

**Comment by fr33co** [comment]
Ok, thanks. I'll check that. 

Note: I made some changes in the code to work on Django 1.7
