### ISSUE TITLE
Integration issue with mandrill

### ISSUE THREAD

**Issue by X17** [arneb/django-campaign#4]
i am trying to implement via mandrill got stuck at this error

**Comment by X17** [comment]
ValueError at /admin/campaign/campaign/1/send/
Empty module name
Request Method:	POST
Request URL:	http://localhost:8002/admin/campaign/campaign/1/send/
Django Version:	1.7
Exception Type:	ValueError
Exception Value:	
Empty module name
Exception Location:***/local/lib/python2.7/site-packages/campaign/context.py in get_mail_processors, line 18

**Comment by X17** [comment]
The issue is 

for path in getattr(settings, 'CAMPAIGN_CONTEXT_PROCESSORS',('campaign.context_processors.recipient')):
            i = path.rfind('.')
            module, attr = path[:i], path[i+1:]
>> returns an empty value for path 

if i put string directly it works.
            module, attr = 'campaign.context_processors','recipient_dict'

**Comment by arneb** [comment]
Which Django Version are you using?
Please show your CAMPAIGN_CONTEXT_PROCESSORS setting (```./manage.py diffsettings | grep CAMPAIGN``` for example).

**Comment by X17** [comment]
CAMPAIGN_BACKEND = 'campaign.backends.mandrill_api'  ###
CAMPAIGN_CONTEXT_PROCESSORS = 'campaign.context_processors.recipient_dict'  ###
CAMPAIGN_FROM_EMAIL = 'foo@domain.com'  ###

**Comment by arneb** [comment]
> CAMPAIGN_CONTEXT_PROCESSORS = 'campaign.context_processors.recipient_dict'

This setting should be a tuple:

```
CAMPAIGN_CONTEXT_PROCESSORS = ('campaign.context_processors.recipient_dict',)
```

**Comment by X17** [comment]
Ahhhh.... feeling kinda dumb.

Thanks for correcting me, though i worked it around but yeah this the correct way.


One more help, where can i set the Sender's Name  in case of mandrill

**Comment by arneb** [comment]
> one last thing from where does it pick the sender's name

By default it takes the sender name configured in the mandrill web user-interface (where you get your api key from). But you can override it with the following setting (I've included some more options as examples):

```
MANDRILL_API_SETTINGS = {
    "from_name": "My Sender Name",
    #"tracking_domain": "newsletter.mydomain.com",
    #"auto_text": False,
    #"auto_html": False,
    #"view_content_link": False,
    #"track_opens": True,
    #"important": False,
}
```

**Comment by X17** [comment]
Is there any feature to add tags to separate campaigns / mailing list . if, not any suggestion how to go about it.

**Comment by arneb** [comment]
there is no feature to add tags and it is not planned to add such a feature. 
maybe you can use django-taggit to add tags.

**Comment by X17** [comment]
Are you writing in reference to mandrill tags as their api supports tags which marks every mail.

I am looking for http://help.mandrill.com/entries/28563573-How-do-I-use-tags-in-Mandrill

**Comment by arneb** [comment]
ok, I misunderstood the question. I have to take a look into it ...

**Comment by X17** [comment]
i have added clarity into my previous comment for more clarity, have a look.

**Comment by X17** [comment]
>Suggestion : Tags will be passed just like the sender's name instead of hardcode if we can give dynamic

MANDRILL_API_SETTINGS = {
    **"tags": ["foo_variable" ],**
    #"from_name": "My Sender Name",
    #"tracking_domain": "newsletter.mydomain.com",
    #"auto_text": False,
    #"auto_html": False,
    #"view_content_link": False,
    #"track_opens": True,
    #"important": False,
}

**Comment by X17** [comment]
@arneb any progress???

**Comment by bashu** [comment]
if someone interested here is another fork https://github.com/bashu/fluentcms-campaign

**Comment by arneb** [comment]
0.3.0 is now released
