### ISSUE TITLE
Django 1.7 ImportError: cannot import name simplejson

### ISSUE THREAD

**Issue by mirzadelic** [arneb/django-campaign#5]
Error:
```python
File "/Users/mirzadelic/test/virtualenv/lib/python2.7/site-packages/campaign/fields.py", line 4, in <module>
    from django.utils import simplejson
ImportError: cannot import name simplejson
```
when install from pip.. but when clone, it works..

**Comment by arneb** [comment]
already fixed, please clone from the git repo until version 0.3.0 is ready for a release. the old 0.2 release on pypi is not compatible with Django 1.7+

https://github.com/arneb/django-campaign/commit/ee587135f880181c87071e20866af90eef977d43
